const messages: Record<string, string> = {
    AUTH_INVALID_CREDENTIALS: 'El email o la contraseña no son correctos.', AUTH_REQUIRED: 'Tu sesión venció. Volvé a ingresar.', NETWORK_ERROR: 'No pudimos conectar. Revisá tu conexión e intentá nuevamente.',
    PRODUCT_SLUG_EXISTS: 'Ya existe un producto con ese slug.', PRODUCT_SKU_EXISTS: 'Ya existe un producto con ese SKU.', PRODUCT_ATTRIBUTE_REQUIRED: 'Completá las especificaciones requeridas antes de publicar.', PRODUCT_ATTRIBUTE_INVALID: 'Revisá las especificaciones de la categoría seleccionada.', PRODUCT_IMAGE_INVALID: 'Revisá las URLs, textos alternativos y la imagen principal.', PRODUCT_PRICE_INVALID: 'Revisá el precio y el precio anterior: debe ser mayor al actual.', PRODUCT_NOT_PUBLISHABLE: 'La categoría debe estar activa para publicar.', PRODUCT_CATEGORY_INVALID: 'Seleccioná una categoría válida.', PRODUCT_BRAND_INVALID: 'Seleccioná una marca válida.',
    CATEGORY_CYCLE: 'La categoría no puede ser su propio padre ni depender de un descendiente.', CATEGORY_IN_USE: 'La categoría tiene referencias. Desactivala o revisá sus relaciones.', BRAND_IN_USE: 'La marca está en uso. Podés desactivarla.', ATTRIBUTE_IN_USE: 'El atributo está en uso y no admite este cambio.', OPTION_IN_USE: 'La opción está en uso. Podés modificar su nombre u orden.', ASSOCIATION_IN_USE: 'La asociación tiene valores en productos y no puede eliminarse.', ATTRIBUTE_OPTIONS_REQUIRED: 'Un atributo de opciones activo necesita al menos una opción.', ACTIVE_PRODUCTS_EXIST: 'Hay productos activos. Desactivalos antes de cambiar esta regla.', ATTRIBUTE_TYPE_MISMATCH: 'El tipo de atributo no admite esa operación.', ATTRIBUTE_INACTIVE: 'Activá primero el atributo.', OPTION_ALREADY_EXISTS: 'Ya existe esa opción.', ASSOCIATION_ALREADY_EXISTS: 'Ese atributo ya está asociado.', CATEGORY_SLUG_EXISTS: 'Ya existe una categoría con ese slug.', BRAND_SLUG_EXISTS: 'Ya existe una marca con ese slug.', ATTRIBUTE_SLUG_EXISTS: 'Ya existe un atributo con ese slug.',
    VALIDATION_ERROR: 'Revisá los campos indicados y sus formatos.', RATE_LIMITED: 'Se realizaron demasiados intentos. Esperá unos minutos.', CSRF_REJECTED: 'No pudimos verificar la solicitud. Recargá la página.', CONCURRENT_MODIFICATION: 'Otro cambio coincidió con este. Revisá los datos e intentá nuevamente.'
};
export class ApiFailure extends Error {
    constructor(public code: string, public status = 0, public details: Record<string, unknown> = {}) { super(messages[code] ?? (status === 404 ? 'El registro ya no está disponible.' : 'No pudimos completar la operación. Intentá nuevamente.')); }
}
export function errorMessage(error: unknown) { return error instanceof ApiFailure ? error.message : 'No pudimos completar la operación. Intentá nuevamente.'; }

export function fieldErrors(error:unknown):Record<string,string>{if(!(error instanceof ApiFailure))return {};const fields=error.details.fields;if(!Array.isArray(fields))return {};return Object.fromEntries(fields.filter((field):field is string=>typeof field==='string'&&field.length>0).map(field=>[field.split('.')[0]!,'Revisá el formato y el valor de este campo.']));}
